### ISSUE TITLE
Additional exercises to port

### ISSUE THREAD

**Issue by BNAndras** [exercism/red#112]
- [ ] Bottle Song
- [ ] Flatten Array
- [x] Isogram
- [ ] Luhn
- [ ] Proverb
- [ ] Queen Attack
- [ ] Robot Simulator
- [ ] Sieve
- [x] Allergies
- [x] Binary Search
- [x] Collatz Conjecture
- [x] Difference of Squares
- [x] Eliud's Eggs
- [x] Grains
- [x] Hamming
- [x] Nucleotide Count
- [x] RNA Transcription
- [x] Scrabble Score
- [x] Square Root
- [x] Triangle

I've ported all of these to other tracks in the last few months so they'll be fresh in my head.

**Comment by loziniak** [comment]
Great work, thank you.

**Comment by BNAndras** [comment]
https://exercism.org/challenges/48in24/implementation_status lists an active view of all the tracks showing the status of exercises featured in #48in24.  We're coming up on raindrops next week so in three weeks, list-ops is the first exercise not ported to Red. I'll work on that next and then acronym.

Of the open PRs, Hamming isn't featured until week 34 and Collatz Conjecture isn't until week 44. Scrabble Score isn't featured at all so it has no priority whatsoever.

**Comment by BNAndras** [comment]
If you want, I can co-maintain and take care of the small stuff, deferring any big-picture stuff to you.
