### ISSUE TITLE
Invalid .meta/config.json file for hello-world exercise

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/red#13]
The [`.meta/config.json` file](https://github.com/exercism/red/blob/main/exercises/practice/hello-world/.meta/config.json) has invalid  JSON (trailing comma). See https://github.com/exercism/website/issues/563

**Comment by loziniak** [comment]
Thanks a lot! I had this feeling that JSON allowed trailing commas at some point. Seems it had to be JavaScript, or even PHP, a mess :-) That's why I fell in love with Red's delimiter-less blocks :-)

**Comment by ErikSchierboom** [comment]
Officially, JSON does not allow trailing comma's, but some JSON parsers secretly allow it. Ours doesn't :)

**Comment by loziniak** [comment]
Fixed by #12 .
