### ISSUE TITLE
Syntax highlighting not working

### ISSUE THREAD

**Issue by BNAndras** [exercism/red#136]
@ErikSchierboom, I'm not seeing syntax highlighting on the website (see below). In the config, `highlightjs_language` is set to "red", but https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md suggests we use https://github.com/oldes/highlightjs-redbol. Is there anything I need to do on my end to enable the syntax highlighting through that third-party grammar

![Red snippet](https://github.com/exercism/red/assets/20251272/0d4e07f9-13e8-458a-8313-eb64451203d6)

**Comment by ErikSchierboom** [comment]
https://github.com/exercism/website/pull/6802
