### ISSUE TITLE
Test of reverse string trys to test %.meta/example.red instead of %reverse-string.red

### ISSUE THREAD

**Issue by Eisenaxt** [exercism/red#156]
The test for the reverse-string-Exercise outputs an error message that the file %.meta/example.red could not be found.

Looks like the wrong line is commented out:

https://github.com/exercism/red/blob/266ff9b9aedc3650ffe67264071bafece6fbc415/exercises/practice/reverse-string/reverse-string-test.red#L8-L9

**Comment by BNAndras** [comment]
That's my bad. It looks like that's the only exercise with that issue so I'll fix it now.

**Comment by BNAndras** [comment]
Okay, I pushed an update. You should get a prompt on the website in a few minutes about updating the exercise.
