### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by loziniak** [exercism/red#48]
Update `.github/workflows/ci.yml` and `.github/workflows/pr.ci.yml` according to [documentation](https://exercism.org/docs/building/tracks/ci).

Implement testing entire project, or just updated exercises. Obvious test is _"do provided examples pass the tests?"_ This would also test the test scripts.

**Comment by ErikSchierboom** [comment]
[PR opened](https://github.com/exercism/red/pull/65). There is a minor fix needed in the test runner for CI to become green.
