### ISSUE TITLE
Decide on testing approach

### ISSUE THREAD

**Issue by loziniak** [exercism/red#5]
How will we do exercise tests?

[from gitter](https://gitter.im/red/help?at=602314ab32e01b4f7186c44f):
> do we want a simple test runner

**Comment by loziniak** [comment]
I think Red is sufficiently capable to use just pure Red for testing. Perhaps some patterns emerge after couple exercises, then we'll just apply DRY principle and distill some testing code?

There is [quick-test](https://github.com/red/red/tree/master/quick-test), but It seems there's code in Rebol there. Are there any other test suites? I use this simple script of mine for testing: [test.red](https://github.com/loziniak/red-scripts/blob/master/test.red), and it's [used like this](https://github.com/loziniak/red-scripts/blob/master/json_test.red)

**Comment by greggirwin** [comment]
In the very near future (we hope) the Red DL will be the prebuilt console directly, so you can run instantly, but it's not that way yet.

Agreed on testing. I roll special case testers, and we'll find what works well there. I don't think quick-test is the best choice for this purpose.

**Comment by loziniak** [comment]
> Agreed on testing. I roll special case testers, and we'll find what works well there. I don't think quick-test is the best choice for this purpose.

Ok, so we have it figured out. Example: [hello-world-test.red@a4cb921d](https://github.com/exercism/red/blob/a4cb921d857f300ce18232a5067b02c6f068e59e/exercises/practice/hello-world/hello-world-test.red)

**Comment by greggirwin** [comment]
Great. Here's a standard test func I use as a baseline in a number of places:
```
	test: func [block expected-result /local res err] [
		if error? set/any 'err try [
			print [mold/only :block newline tab mold res: do block]
			if res <> expected-result [print [tab 'FAILED! tab 'expected mold expected-result]]
		][
			print [mold/only :block newline tab "ERROR!" mold err]
		]
	]
```
