### ISSUE TITLE
Launch Red track

### ISSUE THREAD

**Issue by loziniak** [exercism/red#64]
It seems we have [everything](https://exercism.org/docs/building/tracks/new) ready, except #48 - Continuous Integration. @ErikSchierboom [said](https://exercism-team.slack.com/archives/GC3K95MRR/p1660314760297619) he can help with scripts and GitHub Actions, once we implement automated testing of all exercises at once.

**Comment by ErikSchierboom** [comment]
[PR opened](https://github.com/exercism/red/pull/65)

**Comment by loziniak** [comment]
Now, that PR #65 is merged, next steps to lanuch can be taken.

**Comment by loziniak** [comment]
@ErikSchierboom what's next?

**Comment by ErikSchierboom** [comment]
While not a hard requirement, a nice improvement might be to customize the snippet extractor to skip over comments and such. See https://exercism.org/docs/building/tooling/snippet-extractor and https://github.com/exercism/snippet-extractor/#add-your-language.

**Comment by ErikSchierboom** [comment]
Another would be to support correct line counting. For that, we use the `tokei` library, which unfortunately doesn't support `red` at the moment: https://github.com/XAMPPRocky/tokei#supported-languages Adding a language should not be _that_ hard: https://github.com/XAMPPRocky/tokei/blob/master/CONTRIBUTING.md Fun fact: the recently launched `unison` track did this: https://github.com/XAMPPRocky/tokei/pull/920

**Comment by ErikSchierboom** [comment]
Issues created: #66 and #67
