### ISSUE TITLE
Identify correct line counts

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/red#66]
To count lines of student's solution, we use the `tokei` library, which unfortunately doesn't support red at the moment: https://github.com/XAMPPRocky/tokei#supported-languages

Luckily, adding a language should not be that hard: https://github.com/XAMPPRocky/tokei/blob/master/CONTRIBUTING.md
Fun fact: the recently launched unison track did this: https://github.com/XAMPPRocky/tokei/pull/920

Once the PR has been merged, let me know, as I'll need to redeploy the line counter afterwards.

**Comment by loziniak** [comment]
Just submitted a PR: https://github.com/XAMPPRocky/tokei/pull/958
Do I need to change anything on Exercism side, or just wait for merge on `tokei`?

**Comment by ErikSchierboom** [comment]
@loziniak Ping me when the pr is merged

**Comment by BNAndras** [comment]
Exercism has its own tokei fork now at https://github.com/exercism/tokei so we should make a PR there instead to resolve this issue.

**Comment by loziniak** [comment]
Created a pull-request on Exercism's Tokei repo.
